## 4장 - 선형대수

#### 선형대수는 다차원 구조를 가진 수치의 나열을 다루는 수학의 분야 중 한 가지입니다. 그러한 다차원 구조에는 스칼라, 벡터, 텐서라 부르는 것이 있습니다. 인공지능에서는 매우 많은 수치를 다워야 하는데 선형대수를 이용하면 많은 수치에 대한 처리를 간결한 수식으로 기술할 수 있습니다. 그리고 그 수식은 NumPy로 간단하게 코드로 나타낼 수 있습니다.

### 스칼라

스칼라(scalar)는 1, 5, 1.2, -7 등의 보통의 수치를 말합니다. 이 책에서는 수식에서의 알파벳, 또는 그리스 문자의 소문자는 스칼라를 나타내는 것으로 합니다.

- 스칼라의 표시 예 : a, p, $\alpha$, $\gamma$

### 벡터

벡터는 스칼라를 직선 상에 나열한 것입니다. 이 책의 수식에서는 알파벳의 소문자에 화살표를 올린 것으로 벡터를 나타냅니다.  

벡터에는 위의 $\vec{a}, \vec{p}$와 같이 세로로 수치를 나열하는 세로 벡터와 $\vec{b}, \vec{q}$처럼 가로로 수치를 나열하는 가로 벡터가 있습니다. 이 책에서는 앞으로 가로 벡터를 주로 사용하므로 단지 벡터라고 기술할 때는 가로 벡터를 나타내는 것으로 합니다. 또한, $\vec{p}, \vec{q}$로 볼 수 있듯 벡터의 요소를 변후로 나타낼 때의 첨자 수는 1개입니다.

### 벡터의 구현

벡터는 NumPy의 1차원 배열을 이용해서 나타낼 수 있습니다.

In [1]:
#리스트4.2
import numpy as np

a = np.array([1, 2, 3]) # 1차원 배열로 벡터를 나타낸다
print(a)

b = np.array([-2.4, 0.25, -1.3, 1.8, 0.61])
print(b)

[1 2 3]
[-2.4   0.25 -1.3   1.8   0.61]


수치가 직선 상에 나열되어 있는 걸 확인할 수 있습니다.

### 행렬

헹렬은 스칼라를 격자 형태로 나열한 것으로 예를 들어 다음과 같이 표기합니다.

$$0.12\ \ -0.34\ \ 1.3\ \ 0.81$$
$$-1.4\ \ 0.25\ \ 0.69\ \ -0.41$$
$$0.25\ \ -1.5\ \ -0.15\ \ 1.1$$

행렬에서 수평 방향의 스칼라의 나열을 **행**, 수직 방향의 스칼라의 나열을 **열**이라고 합니다.  

행은 위에서부터 첫 번째, 두 번째, 세 번째, ...로 셉니다. 열은 왼쪽부터 첫 번째 열, 두 번째 열, 세 번째 열, ...로 셉니다. 또한, 행이 $m$개, 열이 $n$개 나열하는 행렬을 $m × n$ 행렬로 표현합니다.

### 행렬의 구현

NumPy의 2차원 배열을 이용해서 행렬을 표현할 수 있습니다.

In [2]:
#리스트4.3
import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6]]) # 2x3의 행렬
print(a)

b = np.array([[0.21, 0.14],
             [-1.3, 0.81],
             [0.12, -2.1]]) # 3x2의 행렬
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


수치가 격자 형태로 나열된 걸 확인할 수 있습니다.

### 텐서

텐서는 스칼라를 여러 개의 차원으로 나열한 것으로 스칼라, 벡터, 행렬을 포함합니다.  
각 요소에 붙은 첨자의 수를 그 텐서의 차원수라고 말합니다 스칼라에는 첨자가 없으므로 0차원 텐서, 벡터는 참가자 첨자가 1개이므로 1차원 텐서, 행렬은 첨자가 2개이므로 2차원 텐서입니다. 더욱 고차원인 것은 3차원 텐서, 4차원 텐서...가 됩니다.

### 텐서의 구현

NumPy의 다차원 배열을 이용하면 3차원 텐서를 구현할 수 있습니다.

In [3]:
#리스트4.4
import numpy as np

a = np.array([[[0, 1, 2, 3],
              [2, 3, 4, 5],
              [4, 5, 6, 7]],
              [[1, 2, 3, 4],
               [3, 4, 5, 6],
               [5, 6, 7, 8]]]) # (2, 3, 4)의 3차원 텐서
print(a)

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


행렬이 2개 나열되어 있는 것을 확인할 수 있습니다. 코드에서 a는 3차원 텐서입니다. NumPy의 다차원 배열에 의해 더욱 층수가 많은 텐서를 표현할 수도 있습니다.

### 내적

내적은 벡터끼리의 곱의 한 종류인데 각 요소끼리 곱한 값을 총합해서 정의합니다.

$$\vec{a} = (a_1, a_2,ㆍㆍㆍ, a_n)$$
$$\vec{b} = (b_1, b_2,ㆍㆍㆍ, b_n)$$

위와 같을 때, $\vec{a}$와 $\vec{b}$의 내적이 $\vec{a}$ㆍ$\vec{b}$로 표시되게 하면 다음과 같습니다.

$$\vec{a}ㆍ\vec{b} = (a_1, a_2,ㆍㆍㆍ, a_n)ㆍ(b_1, b_2,ㆍㆍㆍ, b_n)$$
$$= (a_1b_1 ＋ a_2b_2 ＋ㆍㆍㆍ＋ a_nb_n)$$
$$= \sum_{k=1}^n a_kb_k$$

내적을 구할 때는 두 개의 벡터의 요소 수가 같아야 합니다. 내적은 삼각함수를 사용해 구하는 방법이 있는데 이것에 대해서는 이후에 설명합니다.

내적은 NumPy의 **dot()** 함수로 간단하게 구현할 수 있습니다. 또한, **sum()** 함수를 사용해서 각 요소의 곱의 총합으로도 구할 수 있습니다.

In [1]:
#리스트4.6
import numpy as np

a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print("--- dot() 함수 ---")
print(np.dot(a, b)) # dot() 함수에 의한 내적
print("--- 곱의 총합 ---")
print(np.sum(a * b)) # 곱의 총합에 의한 내적

--- dot() 함수 ---
10
--- 곱의 총합 ---
10


**dot()** 함수, 곱의 총합 모두 같은 결과가 나왔습니다. 내적은 예를 들어 두 개 벡터의 상관관계를 구할 때 등에 사용합니다. 상관관계에 대해서는 이후에서 설명합니다.

### 놈(norm)

놈은 벡터의 크기를 나타내는 양입니다. 인공지능에서 자주 쓰이는 놈으로는 $L^2$ 놈과 $L^1$ 놈이 있습니다.

### $L^2$ 놈

$L^2$ 놈은 다음과 같이 ||$\vec{x}$||$_2$로 나타냅니다. 벡터의 각 요소를 제곱하여 제곱근을 구해 계산합니다.

$$||\vec{x}||_2 = \sqrt{x^2_1 ＋ x^2_2 ＋ㆍㆍㆍ＋ x^2_n}$$
$$= \sqrt{\sum^n_{k=1}x^2_k}$$

### $L^1$ 놈

$L^1$ 놈은 다음과 같이 ||$\vec{x}_1$||로 나타냅니다. 벡터의 각 요소의 절댓값을 더해서 계산합니다.

$$||\vec{x}_1 = |x_1|＋|x_2|＋ㆍㆍㆍ＋|x_n|$$
$$= (\sum^n_{k=1}x^p_k)^\frac{1}{p}$$

놈에는 몇 가지 표시법이 있는데 인공지능에서는 이것들을 필요에 따라 구분해서 하용합니다.

In [5]:
#리스트4.7
import numpy as np

print("놈은 NumPy()의 linalg.norm() 함수를 이용해서 구할 수 있습니다.")

a = np.array([1, 1, -1, -1])

print("--- L2놈 ---")
print(np.linalg.norm(a)) # L2놈(디폴트)
print("--- L1놈 ---")
print(np.linalg.norm(a, 1)) # L1놈

놈은 NumPy()의 linalg.norm() 함수를 이용해서 구할 수 있습니다.
--- L2놈 ---
2.0
--- L1놈 ---
4.0


In [6]:
#리스트4.10
import numpy as np

print("행렬곱을 전체 행과 열의 조합으로 계산하는 건 힘들지만 NumPy의 dot() 함수를 이용하면 간단하게 행렬곱을 계산할 수 있습니다.")

a = np.array([[0, 1, 2],
             [1, 2, 3]])

b = np.array([[2, 1],
             [2, 1],
             [2, 1]])

print(np.dot(a, b))

행렬곱을 전체 행과 열의 조합으로 계산하는 건 힘들지만 NumPy의 dot() 함수를 이용하면 간단하게 행렬곱을 계산할 수 있습니다.
[[ 6  3]
 [12  6]]


In [7]:
#리스트4.11
import numpy as np

print("요소별 곱은 NumPy를 이용해서 구현할 수 있습니다. 요소별 연산에는 스칼라 곱의 연산자와 같은 *를 사용합니다.")

a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

b = np.array([[0, 1, 2],
             [2, 0, 1],
             [1, 2, 0]])

print(a*b)

요소별 곱은 NumPy를 이용해서 구현할 수 있습니다. 요소별 연산에는 스칼라 곱의 연산자와 같은 *를 사용합니다.
[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [8]:
#라스트4.14
import numpy as np

print("NumPy에서는 행렬을 나타내는 배열명의 뒤에 .T를 붙이면 전치가 됩니다.")

a = np.array([[1, 2, 3],
             [4, 5, 6]]) # 행렬

print(a.T) # 전치

NumPy에서는 행렬을 나타내는 배열명의 뒤에 .T를 붙이면 전치가 됩니다.
[[1 4]
 [2 5]
 [3 6]]


In [1]:
#리스트4.15
import numpy as np

a = np.array([[0, 1, 2],
             [1, 2, 3]]) # 2x3의 행렬
b = np.array([[0, 1, 2],
             [1, 2, 3]]) # 2x3의 행렬, 이대로는 행렬곱을 할 수 없다.

# print(np.dot(a, b)) # 전치하지 않고 행렬곱을 취하면 에러
print(np.dot(a, b.T)) # 전치에 의해 행렬곱이 가능해짐

[[ 5  8]
 [ 8 14]]


In [2]:
#리스트4.18
import numpy as np

print("NumPy에서는 eye() 함수로 단위행렬을 작성할 수 있습니다. eye() 함수에 전달하는 인수는 단위행렬의 크기를 나타냅니다.")

print(np.eye(2)) # 2x2의 단위 행렬
print()
print(np.eye(3)) # 3x3의 단위 행렬
print()
print(np.eye(4)) # 4x4의 단위 행렬

NumPy에서는 eye() 함수로 단위행렬을 작성할 수 있습니다. eye() 함수에 전달하는 인수는 단위행렬의 크기를 나타냅니다.
[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
#리스트4.19
import numpy as np

print("행렬에 따라서는 역행렬이 존재하지 않을 수 있습니다. 역행렬이 존재할지 여부는 행렬식에 의해 판정할 수 있습니다. NumPy의 linalg.det() 함수에 의해 행렬식을 구할 수 있습니다.")

a = np.array([[1, 2],
             [3, 4]])
print(np.linalg.det(a)) # 행렬식이 0이 되지 않는 경우

b = np.array([[1, 2],
             [0, 0]])
print(np.linalg.det(b)) # 행렬식이 0이 되는 경우

행렬에 따라서는 역행렬이 존재하지 않을 수 있습니다. 역행렬이 존재할지 여부는 행렬식에 의해 판정할 수 있습니다. NumPy의 linalg.det() 함수에 의해 행렬식을 구할 수 있습니다.
-2.0000000000000004
0.0


In [7]:
#리스트4.20
import numpy as np

print("역행렬이 존재하는 경우, NumPy의 linalg.inv() 함수로 역행렬을 구할 수 있습니다.")
print("역행렬은 인공지능에서 변수끼리 상관관계를 알아보는 회귀 분석에 사용됩니다.")

a = np.array([[1, 2],
             [3, 4]])
print(np.linalg.inv(a)) # 역행렬

b = np.array([[1, 2],
             [0, 0]])
# print(np.linalg.inv(b)) # 역행렬이 존재하지 않으므로 에러가 난다

역행렬이 존재하는 경우, NumPy의 linalg.inv() 함수로 역행렬을 구할 수 있습니다.
역행렬은 인공지능에서 변수끼리 상관관계를 알아보는 회귀 분석에 사용됩니다.
[[-2.   1. ]
 [ 1.5 -0.5]]
