In [1]:
#리스트4.2
import numpy as np

print("벡터는 NumPy의 1차원 배열을 이용해서 나타낼 수 있습니다.")

a = np.array([1, 2, 3]) # 1차원 배열로 벡터를 나타낸다
print(a)

b = np.array([-2.4, 0.25, -1.3, 1.8, 0.61])
print(b)

벡터는 NumPy의 1차원 배열을 이용해서 나타낼 수 있습니다.
[1 2 3]
[-2.4   0.25 -1.3   1.8   0.61]


In [2]:
#리스트4.3
import numpy as np

print("NumPy의 2차원 배열을 이용해서 행렬을 표현할 수 있습니다.")

a = np.array([[1, 2, 3],
             [4, 5, 6]]) # 2x3의 행렬
print(a)

b = np.array([[0.21, 0.14],
             [-1.3, 0.81],
             [0.12, -2.1]]) # 3x2의 행렬
print(b)

NumPy의 2차원 배열을 이용해서 행렬을 표현할 수 있습니다.
[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


In [3]:
#리스트4.4
import numpy as np

print("NumPy의 다차원 배열을 이용하면 3차원 텐서를 구현할 수 있습니다.")

a = np.array([[[0, 1, 2, 3],
              [2, 3, 4, 5],
              [4, 5, 6, 7]],
              [[1, 2, 3, 4],
               [3, 4, 5, 6],
               [5, 6, 7, 8]]]) # (2, 3, 4)의 3차원 텐서
print(a)

NumPy의 다차원 배열을 이용하면 3차원 텐서를 구현할 수 있습니다.
[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


In [4]:
#리스트4.6
import numpy as np

print("벡터의 내적은 NumPy의 dot() 함수로 간단하게 구현할 수 있습니다. 또한, sum() 함수를 사용해서 각 요소의 곱의 총합으로도 구할 수 있습니다.")

a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print("--- dot() 함수 ---")
print(np.dot(a, b)) # dot() 함수에 의한 내적
print("--- 곱의 총합 ---")
print(np.sum(a * b)) # 곱의 총합에 의한 내적

벡터의 내적은 NumPy의 dot() 함수로 간단하게 구현할 수 있습니다. 또한, sum() 함수를 사용해서 각 요소의 곱의 총합으로도 구할 수 있습니다.
--- dot() 함수 ---
10
--- 곱의 총합 ---
10


In [5]:
#리스트4.7
import numpy as np

print("놈은 NumPy()의 linalg.norm() 함수를 이용해서 구할 수 있습니다.")

a = np.array([1, 1, -1, -1])

print("--- L2놈 ---")
print(np.linalg.norm(a)) # L2놈(디폴트)
print("--- L1놈 ---")
print(np.linalg.norm(a, 1)) # L1놈

놈은 NumPy()의 linalg.norm() 함수를 이용해서 구할 수 있습니다.
--- L2놈 ---
2.0
--- L1놈 ---
4.0


In [6]:
#리스트4.10
import numpy as np

print("행렬곱을 전체 행과 열의 조합으로 계산하는 건 힘들지만 NumPy의 dot() 함수를 이용하면 간단하게 행렬곱을 계산할 수 있습니다.")

a = np.array([[0, 1, 2],
             [1, 2, 3]])

b = np.array([[2, 1],
             [2, 1],
             [2, 1]])

print(np.dot(a, b))

행렬곱을 전체 행과 열의 조합으로 계산하는 건 힘들지만 NumPy의 dot() 함수를 이용하면 간단하게 행렬곱을 계산할 수 있습니다.
[[ 6  3]
 [12  6]]


In [7]:
#리스트4.11
import numpy as np

print("요소별 곱은 NumPy를 이용해서 구현할 수 있습니다. 요소별 연산에는 스칼라 곱의 연산자와 같은 *를 사용합니다.")

a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

b = np.array([[0, 1, 2],
             [2, 0, 1],
             [1, 2, 0]])

print(a*b)

요소별 곱은 NumPy를 이용해서 구현할 수 있습니다. 요소별 연산에는 스칼라 곱의 연산자와 같은 *를 사용합니다.
[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [8]:
#라스트4.14
import numpy as np

print("NumPy에서는 행렬을 나타내는 배열명의 뒤에 .T를 붙이면 전치가 됩니다.")

a = np.array([[1, 2, 3],
             [4, 5, 6]]) # 행렬

print(a.T) # 전치

NumPy에서는 행렬을 나타내는 배열명의 뒤에 .T를 붙이면 전치가 됩니다.
[[1 4]
 [2 5]
 [3 6]]


In [9]:
#리스트4.15
import numpy as np

a = np.array([[0, 1, 2],
             [1, 2, 3]]) # 2x3의 행렬
b = np.array([[0, 1, 2],
             [1, 2, 3]]) # 2x3의 행렬, 이대로는 행렬곱을 할 수 없다.

# print(np.dot(a, b)) # 전치하지 않고 행렬곱을 취하면 에러
print(np.dot(a, b.T)) # 전치에 의해 행렬곱이 가능해짐

[[ 5  8]
 [ 8 14]]
